// src/lib/List.svelte
<script lang="ts">
  import type { ItemObject } from '../vite-env';
  import { numberToMark } from 'pinyin-utils';
  import { selected } from './store';

  export let items: ItemObject[] = [];
  export let simplified = true;

  $: marks = items.map(({ hanzi, pinyin, def }) => [
    hanzi,
    numberToMark(pinyin),
    def,
  ]);
</script>

{#if marks.length}
  <ul
    class="absolute z-10 mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm"
    id="options"
    role="listbox"
  >
    {#each marks as [hanzi, pinyin, def]}
      <li
        class="relative py-2 pl-3 pr-9 text-gray-900 hover:bg-slate-200 cursor-pointer"
        id="option-0"
        role="option"
        aria-selected="false"
        tabindex="-1"
        on:click={() => {
          selected.set({ hanzi, pinyin, def });
          marks = [];
        }}
        on:keypress={(e) => {
          if (e.key === 'Enter')
            selected.set({ hanzi, pinyin, def });
        }}
      >
        <span class="block truncate"
          >{hanzi.split(' ')[simplified ? 1 : 0]} - {pinyin} - {def}</span
        >
      </li>
    {/each}
  </ul>
{/if}

// src/v2/List.tsx
import { numberToMark } from 'pinyin-utils';
import { store } from './store';
import { ItemObject } from '../vite-env';

interface ListProps {
  items: ItemObject[];
}

const List = (p: ListProps) => {
  const s = store.getState();

  const handleClick = (
    _hanzi: string,
    pinyin: string,
    def: string,
  ) => {
    const hanzi = _hanzi.split(' ')[s.simplified ? 1 : 0];
    s.setStore({ selected: { hanzi, pinyin, def } });
  };

  return (
    <ul
      className="absolute z-10 mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm"
      id="options"
      role="listbox"
    >
      {p.items?.map(({ hanzi, pinyin, def }, i) => (
        <li
          className="relative py-2 pl-3 pr-9 text-gray-900 hover:bg-slate-200 cursor-pointer"
          id={`option-${i}`}
          key={hanzi}
          role="option"
          tabIndex={i}
          onClick={() => handleClick(hanzi, pinyin, def)}
        >
          <span className="block truncate">
            {hanzi.split(' ')[s.simplified ? 1 : 0]} -{' '}
            {numberToMark(pinyin)} - {def}
          </span>
        </li>
      ))}
    </ul>
  );
};

export default List;
